### ISSUE TITLE
工具无法使用burp的代理

### ISSUE THREAD

**Issue by canc3s** [shack2/SuperSQLInjectionV1#5]
工具可以正确设置并验证burp的代理
![图片](https://user-images.githubusercontent.com/36873866/69609586-d5534680-1064-11ea-82ff-f86894c3139d.png)
![图片](https://user-images.githubusercontent.com/36873866/69609653-f156e800-1064-11ea-9570-812f72039f7c.png)
但无法使用
![图片](https://user-images.githubusercontent.com/36873866/69609702-1e0aff80-1065-11ea-929a-ef874300c4cd.png)
![图片](https://user-images.githubusercontent.com/36873866/69609690-12b7d400-1065-11ea-9b8c-fc2dfd9693a3.png)

**Comment by handbye** [comment]
这个怎么解决的？
